version: '3'
services:
  solr:
    image: solr:8
    ports:
     - "8983:8983"
    # environment:
    #   SOLR_CORE_CONF_DIR: /opt/solr/server/solr/configsets
    command:
     - solr-precreate
    #  - techproducts
    #  - cp -rf /opt/solr/server/solr/configsets /var/solr/data
    volumes:
      - ./configsets:/var/solr/data/configsets
