name: Feathers-Solr CI

on:
  push:
    branches: [ master, v3.0.0-pre.1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    services:
      solr:
        image: solr:7.7.3
        ports:
          - 8983:8983
        options: >-
          --health-cmd "curl --fail http://0.0.0.0:8983/solr/admin/cores || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: "Set some postgres settings"
      run: |
          docker exec ${{ job.services.solr.id }} sh -c 'solr create_core -c gettingstarted'
    - run: |
        echo "Checking on the solr instance"
        curl http://localhost:8983/solr/admin/cores
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run compile --if-present
    - run: npm install -g istanbul
    - run: npm install --save-dev mocha chai
    - run: npm install -g coveralls
    - run: node_modules/.bin/istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --colors --reporter spec test/

